# Kubernetes deployment file for the Studio Project web service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-project-service
spec:
  replicas: 2  # Only deploy one instance of the web service
  selector:
    matchLabels:
      app: studio-project-service
  template:
    metadata:
      labels:
        app: studio-project-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: studio-project-service
          image: twoshot.azurecr.io/studio-project-service:b39b50d33085459b78b1ddda284602f09d518197  # Use the latest version of the Docker image
          ports:
            - containerPort: 3000  # Expose port 3000 on the container

          # scan websocket endpoint on port 3000 to check if the service is up - ignore 404 errors
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"  # Set the PORT environment variable to 3000

            - name: AWS_REGION
              value: arn:aws:sqs:us-east-1:858863279228:deduplicate-audio-studio-project.fifo
            - name: DEDUPLICATE_AUDIO_SQS_QUEUE_URL
              value: https://sqs.us-east-1.amazonaws.com/858863279228/deduplicate-audio-studio-project.fifo

            # DB connection details
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "twoshot.postgres.database.azure.com"
            - name: DB_SSL
              value: "true"
            - name: DB_NAME
              value: twoshot
            - name: DB_USER
              value: "twoshot"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: postgres-password

            - name: TWOSHOT_AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: signing-key-public
            - name: TWOSHOT_API_BASE_PATH
              value: http://twoshot.default.svc.cluster.local:8080

---
apiVersion: v1
kind: Service
metadata:
  name: studio-project-service
spec:
  type: NodePort  # Use a NodePort service type to expose the web service on the cluster's nodes
  selector:
    app: studio-project-service
  ports:
    - protocol: TCP
      port: 3000  # Expose port 3000 on the service
      targetPort: 3000  # Target the container's port 3000 for incoming traffic